apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-todo
spec:
  selector:
    matchLabels:
      app: kube-todo
  template:
    metadata:
      labels:
        app: kube-todo
    spec:
      volumes:
        - name: todo-data
          persistentVolumeClaim:
            claimName: todo-pvc
      containers:
        - name: kube-todo
          image: lonias/kube-todo:0.0.6
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
              ephemeral-storage: "256Mi"
          volumeMounts:
            - name: todo-data
              mountPath: /app/public
