apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-todo
  labels:
    name: kube-todo
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-todo
                port:
                  number: 2345
          - pathType: Prefix
            path: "/image-of-the-day"
            backend:
              service:
                name: kube-todo
                port:
                  number: 2345
