apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  volumeName: todo-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
